Some changes from DD

diff --git a/Mix/trunk/configure b/Mix/trunk/configure
--- a/Mix/trunk/configure
+++ b/Mix/trunk/configure
@@ -12230,71 +12230,6 @@ echo "$as_me: error: Xerces-C libs NOT found - please use --with-xml-lib" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-{ echo "$as_me:$LINENO: checking if libxerces-depdom is needed" >&5
-echo $ECHO_N "checking if libxerces-depdom is needed... $ECHO_C" >&6; }
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-#include "util/XercesDefs.hpp"
-#include "util/PlatformUtils.hpp"
-#if (XERCES_VERSION_MAJOR >1)
-    #include <dom/deprecated/DOM.hpp>
-    #include <dom/deprecated/DOMParser.hpp>
-#else
-    #include <dom/DOM.hpp>
-    #include <parsers/DOMParser.hpp>
-#endif
-#if (_XERCES_VERSION >= 20200)
-    XERCES_CPP_NAMESPACE_USE
-#endif
-
-int
-main ()
-{
-XMLPlatformUtils::Initialize();		DOM_Document doc=DOM_Document::createDocument();
-
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  { echo "$as_me:$LINENO: result: No" >&5
-echo "${ECHO_T}No" >&6; }
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	{ echo "$as_me:$LINENO: result: Yes" >&5
-echo "${ECHO_T}Yes" >&6; }
-LIBS="$LIBS -lxerces-depdom"
-
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -13387,6 +13322,72 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+    { echo "$as_me:$LINENO: checking whether MYSQL_OPT_RECONNECT is declared" >&5
+echo $ECHO_N "checking whether MYSQL_OPT_RECONNECT is declared... $ECHO_C" >&6; }
+if test "${ac_cv_have_decl_MYSQL_OPT_RECONNECT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    				#ifdef HAVE_MYSQL_MYSQL_H
+				#include <mysql/mysql.h>
+				#elif defined(HAVE_MYSQL_H)
+				#include <mysql.h>
+				#endif
+
+
+int
+main ()
+{
+#ifndef MYSQL_OPT_RECONNECT
+  (void) MYSQL_OPT_RECONNECT;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_have_decl_MYSQL_OPT_RECONNECT=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_have_decl_MYSQL_OPT_RECONNECT=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_have_decl_MYSQL_OPT_RECONNECT" >&5
+echo "${ECHO_T}$ac_cv_have_decl_MYSQL_OPT_RECONNECT" >&6; }
+if test $ac_cv_have_decl_MYSQL_OPT_RECONNECT = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MYSQL_OPT_RECONNECT
+_ACEOF
+
+fi
 
 LIBS="$saved_LIBS"
 fi
